export const REQUEST_CERTIFICATE_READER = 'REQUEST_CERTIFICATE_READER';
export const SUCCESS_CERTIFICATE_READER = 'SUCCESS_CERTIFICATE_READER';
export const FAIL_CERTIFICATE_READER = 'FAIL_CERTIFICATE_READER';

export const REQUEST_CERTIFICATE_WRITER = 'REQUEST_CERTIFICATE_WRITER';
export const SUCCESS_CERTIFICATE_WRITER = 'SUCCESS_CERTIFICATE_WRITER';
export const FAIL_CERTIFICATE_WRITER = 'FAIL_CERTIFICATE_WRITER';

export const REQUEST_IMAGE_READER = 'REQUEST_IMAGE_READER';
export const SUCCESS_IMAGE_READER = 'SUCCESS_IMAGE_READER';
export const FAIL_IMAGE_READER = 'FAIL_IMAGE_READER';

export const REQUEST_IMAGE_WRITER = 'REQUEST_IMAGE_WRITER';
export const SUCCESS_IMAGE_WRITER = 'SUCCESS_IMAGE_WRITER';
export const FAIL_IMAGE_WRITER = 'FAIL_IMAGE_WRITER';

export const REQUEST_LINK_READER = 'REQUEST_LINK_READER';
export const SUCCESS_LINK_READER = 'SUCCESS_LINK_READER';
export const FAIL_LINK_READER = 'FAIL_LINK_READER';

export const REQUEST_LINK_WRITER = 'REQUEST_LINK_WRITER';
export const SUCCESS_LINK_WRITER = 'SUCCESS_LINK_WRITER';
export const FAIL_LINK_WRITER = 'FAIL_LINK_WRITER';

export const REQUEST_PROJECT_READER = 'REQUEST_PROJECT_READER';
export const SUCCESS_PROJECT_READER = 'SUCCESS_PROJECT_READER';
export const FAIL_PROJECT_READER = 'FAIL_PROJECT_READER';

export const REQUEST_PROJECT_WRITER = 'REQUEST_PROJECT_WRITER';
export const SUCCESS_PROJECT_WRITER = 'SUCCESS_PROJECT_WRITER';
export const FAIL_PROJECT_WRITER = 'FAIL_PROJECT_WRITER';

export const REQUEST_STUDY_READER = 'REQUEST_STUDY_READER';
export const SUCCESS_STUDY_READER = 'SUCCESS_STUDY_READER';
export const FAIL_STUDY_READER = 'FAIL_STUDY_READER';

export const REQUEST_STUDY_WRITER = 'REQUEST_STUDY_WRITER';
export const SUCCESS_STUDY_WRITER = 'SUCCESS_STUDY_WRITER';
export const FAIL_STUDY_WRITER = 'FAIL_STUDY_WRITER';

export const REQUEST_TECH_READER = 'REQUEST_TECH_READER';
export const SUCCESS_TECH_READER = 'SUCCESS_TECH_READER';
export const FAIL_TECH_READER = 'FAIL_TECH_READER';

export const REQUEST_TECH_WRITER = 'REQUEST_TECH_WRITER';
export const SUCCESS_TECH_WRITER = 'SUCCESS_TECH_WRITER';
export const FAIL_TECH_WRITER = 'FAIL_TECH_WRITER';

export const REQUEST_WORK_READER = 'REQUEST_WORK_READER';
export const SUCCESS_WORK_READER = 'SUCCESS_WORK_READER';
export const FAIL_WORK_READER = 'FAIL_WORK_READER';

export const REQUEST_WORK_WRITER = 'REQUEST_WORK_WRITER';
export const SUCCESS_WORK_WRITER = 'SUCCESS_WORK_WRITER';
export const FAIL_WORK_WRITER = 'FAIL_WORK_WRITER';

export const REQUEST_USER_READER = 'REQUEST_USER_READER';
export const SUCCESS_USER_READER = 'SUCCESS_USER_READER';
export const FAIL_USER_READER = 'FAIL_USER_READER';

export const REQUEST_USER_WRITER = 'REQUEST_USER_WRITER';
export const SUCCESS_USER_WRITER = 'SUCCESS_USER_WRITER';
export const FAIL_USER_WRITER = 'FAIL_USER_WRITER';
